### ISSUE TITLE
在樹狀圖第一層的畫面上方中央加上標題 འཇང་བཀའ་འགྱུར།，標題加上底色

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#1]
希望在樹狀圖第一層(目錄頁)的畫面上方中央加上標題 འཇང་བཀའ་འགྱུར། (深綠色框)，意思是麗江版大藏經甘珠爾。
在這個標題下面加上底色，看起來較為明顯。

![13 1](https://cloud.githubusercontent.com/assets/13195099/11629254/05414d4c-9d32-11e5-8946-be025811f089.PNG)

**Comment by kmsheng** [comment]
fixed in v1.0.1

**Comment by chiehan1** [comment]
Test ok!
Thank you so much!
