### ISSUE TITLE
進階搜尋結果頁面功能

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#13]
1. 每頁顯示20項藏文經名。
2. 可換頁。(像iPhone的google搜尋一樣)

![44 8](https://cloud.githubusercontent.com/assets/13195099/11742760/489222ca-a03d-11e5-9566-c322a730a951.jpg)

第一頁有往下一頁箭頭，第二頁有回上一頁和往下一頁箭頭，第三頁有回第一頁、回上一頁，往下一頁箭頭

**Comment by kmsheng** [comment]
pager 的部分目前不考慮喔 ! (將參考 google image search 的方式)

**Comment by chiehan1** [comment]
了解

**Comment by chiehan1** [comment]
可無限捲動所以不考慮 pager
