### ISSUE TITLE
Search feature not working

### ISSUE THREAD

**Issue by yapcheahshen** [karmapa/AdarshaIos#15]
Version 1.08
Mac mini 2 , iOS 9.2

**Comment by kmsheng** [comment]
Mac mini 2 ?
I thought it was only for mobile & pad.

**Comment by yapcheahshen** [comment]
iPad mini 2

從我的 iPad 傳送

**Comment by kmsheng** [comment]
@yapcheahshen please be more specific about the problem. I've tested it on my ipad2, everything goes fine.

**Comment by yapcheahshen** [comment]
搜尋沒任何反應 (1.0.11 1.0.12 都是)，之前某一版可以的。

2015-12-15 16:46 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
![img_0070](https://cloud.githubusercontent.com/assets/880569/11811314/c110391e-a36f-11e5-9d2d-79022a87ad92.PNG)
@yapcheahshen 你的搜尋是指上圖這裡嗎 ? 我這邊沒辦法重製出來, 看來要借一台 ipad mini2 才有辦法看到錯誤訊息了 ?

**Comment by yapcheahshen** [comment]
我輸入wylie 沒動靜

kmsheng notifications@github.com 於 2015年12月15日 下午9:08 寫道：

**Comment by kmsheng** [comment]
@yapcheahshen 請問 v1.0.20 還是沒動靜嗎 ?

**Comment by yapcheahshen** [comment]
我查出問題了，因為ipad 輸入英文自動將第一個字母大寫，轉wylie 就有問題。

**Comment by kmsheng** [comment]
所以要強制轉小寫嗎？

**Comment by kmsheng** [comment]
wylie 是 case sensitive嗎？

**Comment by yapcheahshen** [comment]
據我所知是只一般藏文只用到小寫，
梵文轉寫會用到大寫。大藏經內有少量梵文，所以還是要能區分大小寫。
http://www.library.gov.bt/IT/wylie.html

你把inputbox 的auto-capitalize 機制關掉吧。
http://stackoverflow.com/questions/6943016/uitextfield-auto-capitalization-type-iphone-app

yap

2015-12-19 19:46 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
請確認 v1.0.21 是否有修正此問題
