### ISSUE TITLE
Transparent brown background only cover top 70% in portrait mode

### ISSUE THREAD

**Issue by yapcheahshen** [karmapa/AdarshaIos#18]
version 1.0.17
on iPad Mini 2, iOS 9.2
![img_0994](https://cloud.githubusercontent.com/assets/1085366/11873136/02b1d7a6-a514-11e5-8e79-1e2fe65ec71f.PNG)

**Comment by kmsheng** [comment]
confirmed

**Comment by yapcheahshen** [comment]
both portrait and landscape not working.
![img_0995](https://cloud.githubusercontent.com/assets/1085366/11894855/f73b6a76-a5b4-11e5-948b-05ebafb67d8c.PNG)
![img_0994](https://cloud.githubusercontent.com/assets/1085366/11894854/f738f00c-a5b4-11e5-8e7f-b2f362d92273.PNG)

**Comment by yapcheahshen** [comment]
both portrait and landscape not working. version 1.0.18
![img_0995](https://cloud.githubusercontent.com/assets/1085366/11894870/1307a922-a5b5-11e5-9e2a-aa23fb182c80.PNG)
![img_0996](https://cloud.githubusercontent.com/assets/1085366/11894871/13091da2-a5b5-11e5-999f-5efcb9903ee2.PNG)
