### ISSUE TITLE
希望更改進階搜尋的鍵盤按鍵名稱

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#19]
進階搜尋頁面的鍵盤，圖中用綠色框起來的按鈕，
希望將英文鍵盤的 "return" 改名為 "search" ;
中文鍵盤的 "換行" 改名為 "搜尋" ;
藏文鍵盤的 "འཕྲེང་འོག་" 改名為 "འཚོལ་" 。

感謝!!
![50 4](https://cloud.githubusercontent.com/assets/13195099/11924149/c8654034-a7e7-11e5-894c-74b77f808141.jpg)

**Comment by kmsheng** [comment]
已在 v1.0.25+ 修正

**Comment by chiehan1** [comment]
Thank you!!
