### ISSUE TITLE
希望進階搜尋後面的欄位和reset按鈕不要被鍵盤遮住

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#20]
在進階搜尋叫出鍵盤後，後面的欄位和最後的 reset 按鈕會被鍵盤遮住，沒辦法向上滾出。
如下列影片檔
https://drive.google.com/open?id=0B7IngcS_Eo5JNU1rWGhPSlIyX3c

希望能像google search一樣，網頁的最底部滾到最後能剛好滾到鍵盤上方，不被遮住。
感謝!!

**Comment by kmsheng** [comment]
已在 v1.0.25+ 修正

**Comment by chiehan1** [comment]
Thank you!!
