### ISSUE TITLE
希望進階搜尋最上方的滾動式選項調整置中

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#22]
進階搜尋最上方的滾動式選項在手機橫擺時會偏離置中，再直立手機後，也會偏離置中，
如下列影片檔
https://drive.google.com/open?id=0B7IngcS_Eo5JM3UtQlhZT1JSRVU

希望能調整讓選項置中。
感謝!!!

**Comment by kmsheng** [comment]
https://github.com/facebook/react-native/issues/3228 # 先用固定寬度的解法來解

**Comment by kmsheng** [comment]
已在 v1.0.25+ 修正

**Comment by chiehan1** [comment]
Thank you!!

**Comment by chiehan1** [comment]
雖然v1.0.25，選項不會被畫面cut掉了，但還是希望手機或ipad橫擺的時候可以置中

**Comment by kmsheng** [comment]
@chiehan1 已在 v1.0.45 修正此問題

**Comment by chiehan1** [comment]
測試ok !!
感謝!!
