### ISSUE TITLE
全文檢索在文字輸入到一半就執行搜尋

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#24]
如下列影片

輸入 ni 後
會先顯示 n 的搜尋結果
接下來才顯示 ni 的搜尋結果

https://youtu.be/N2pYdBoSkqE

是否能延遲執行搜尋的時間
感謝

**Comment by kmsheng** [comment]
fixed in v1.0.27

**Comment by chiehan1** [comment]
Test ok!!
Thank you!!
