### ISSUE TITLE
內文閱覽模式 將背景選擇和工具列的功能放到設定功能鍵裡

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#27]
將**背景選擇**的功能放到設定功能鍵裡，

工具列的功能(如下圖)也都放到設定功能鍵裡。

![default](https://cloud.githubusercontent.com/assets/13195099/11972243/8d1746c8-a984-11e5-97de-0ce81a95aaee.jpg)

**Comment by yapcheahshen** [comment]
1.0.33 字型和行數設定，離開重進又回到預設值，沒有儲存。

**Comment by kmsheng** [comment]
v1.0.35 已修正儲存問題, 同樣問題有再發生歡迎 reopen
