### ISSUE TITLE
內文閱覽模式 原工具列處新增搜尋欄位

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#29]
原工具列處新增搜尋欄位，搜尋欄位名稱為 **Search in Sutra**，欄位周圍底色需配合背景顏色，如下圖是土黃色，當背景是藍色，搜尋欄周圍也變為藍色，背景是白底，搜尋欄周圍變為白底。

![default](https://cloud.githubusercontent.com/assets/13195099/11973913/2ecfa4d2-a99a-11e5-81fc-1c7c408550b3.jpg)

**Comment by kmsheng** [comment]
@chiehan1 這東西應該沒那麼簡單吧? 因為同一個字可能不只一次出現在文章, 所以是不是還要有 next / prev 按鈕?

**Comment by kmsheng** [comment]
@chiehan1 又或者利用鍵盤的搜尋鍵, 每按一次就等同 next, 然後循環到第一個

**Comment by kmsheng** [comment]
Search in sutra 已實作在 v1.0.35
next / prev 行為請開別的 issue 處理。
