### ISSUE TITLE
樹狀圖目錄顯示的項目名稱太長須折行

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#3]
如果樹狀圖目錄的項目名稱超過螢幕屏寬(如綠色框後面的部分名稱超過屏寬)，希望能夠自動折行，才能看到全名

![2](https://cloud.githubusercontent.com/assets/13195099/11629531/b7b307bc-9d33-11e5-93bf-6e1568df8e07.PNG)

**Comment by chiehan1** [comment]
折行比較像是這樣，才能看到完整的經名

![36 3](https://cloud.githubusercontent.com/assets/13195099/11713013/b29e9ce8-9f6b-11e5-93af-ed88b616e0e3.PNG)

**Comment by kmsheng** [comment]
fixed in current version

**Comment by chiehan1** [comment]
有些經文折行以後會有兩行以上

**Comment by chiehan1** [comment]
測試了 v1.0.3
有些經文折行以後會有兩行以上，可以的話，希望兩行以上的經文也能折行以後完整顯示，感謝!

**Comment by kmsheng** [comment]
可以截個圖嗎？

**Comment by chiehan1** [comment]
希望可以像右圖一樣能顯示全部經名
![41 4](https://cloud.githubusercontent.com/assets/13195099/11736440/5d623bf6-a009-11e5-9617-97f20eafbce9.jpg)

**Comment by kmsheng** [comment]
fixed in v1.0.4

**Comment by chiehan1** [comment]
Test ok!
Thank you!!
