### ISSUE TITLE
內文閱覽模式 新增的搜尋欄位關鍵字 支援輸入 Wylie 轉寫

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#30]
內文閱覽模式 新增的搜尋欄位，需支援輸入Wylie轉寫的關鍵字。如下圖綠色框。
感謝!!

![wylie](https://cloud.githubusercontent.com/assets/13195099/11974091/db8376f8-a99b-11e5-9c46-45923a943c86.jpg)

**Comment by kmsheng** [comment]
@yapcheahshen ios 裡的藏文看起來不是等寬字型, 你知道怎麼計算藏文字的寬度嗎 ?

**Comment by yapcheahshen** [comment]
應該沒有等寬的藏文字型。
為何要計算藏文字串寬度？

2015-12-23 19:53 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
@yapcheahshen 因為要 scroll 到該字出現的位置, 所以必須根據字寬與螢幕寬度算出被搜尋的字是出現在第幾行,  iOS 的 UITextView 似乎有類似方法可以取得一個字的 posiiton, React Native 卻沒有。

**Comment by yapcheahshen** [comment]
字寬字高在js應該不好算。將目標element ，設一個 id ，再取得其位置捲過去較簡單。

kmsheng notifications@github.com 於 2015年12月23日 下午8:48 寫道：

**Comment by yapcheahshen** [comment]
http://stackoverflow.com/questions/30096038/react-native-getting-the-position-of-an-element

Yap yapcheahshen@gmail.com 於 2015年12月23日 下午9:00 寫道：

**Comment by kmsheng** [comment]
fixed in v1.0.41
