### ISSUE TITLE
內文閱覽模式的設定功能鍵中 有切換背景的按鈕

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#31]
除了現在的米黃色背景
還有之前的白底
加上水藍色背景
共三種背景色供使用者選擇
水藍色背景圖檔放在下列連結中
https://drive.google.com/drive/folders/0B7IngcS_Eo5JbHZsUlpndWh4Y0U

**Comment by kmsheng** [comment]
fixed in v1.0.36
