### ISSUE TITLE
內文閱覽模式 新增跳到目前經文開頭的按鈕

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#32]
如下圖綠框所示，如果目前的所在段落是 A經，按了按鈕就會跳到A經的開頭。
如果使用者繼續稐動頁面到 B經，按了按鈕則會跳到B經的開頭，以此類推。

![2](https://cloud.githubusercontent.com/assets/13195099/11975045/bbc5d74e-a9a4-11e5-95b6-6b54f71c296b.jpg)

**Comment by kmsheng** [comment]
@yapcheahshen 請問要怎麼樣透過當前的 uti 抓到該篇經文的開頭 ?

**Comment by yapcheahshen** [comment]
先用ksa.toc 抓到目前uti 的breadcrumb
取 breadcrumb 第3層就是 sutra ，再捲到該 vpos

2015-12-23 19:48 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
@yapcheahshen vpos 是用哪種寬度去算的 ? iphone 直接捲到該位置也 ok 嗎 ?

**Comment by yapcheahshen** [comment]
取得經首的vpos ，重新 ksa.fetch 較簡單。

2015-12-23 20:53 GMT+08:00 kmsheng notifications@github.com:

**Comment by chiehan1** [comment]
Test ok in v1.0.35
