### ISSUE TITLE
刪減進階搜尋欄位

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#33]
請刪除下圖框選的八個欄位，不算最上面的滾動式選單，這些欄位分別是

第二欄：xml tag <aname></aname>; json檔 .divisions[i].sutras[i].aname

第三欄：xml tag <sname></sname>; json檔 .divisions[i].sutras[i].sname

第四欄：xml tag <cname></cname>; json檔 .divisions[i].sutras[i].cname

第五欄：xml tag <subject></subject>; json檔 .divisions[i].sutras[i].subject

第九欄：xml tag <purpose></purpose>; json檔 .divisions[i].sutras[i].purpose

第十欄：xml tag <collect></collect>; json檔 .divisions[i].sutras[i].collect

第十一欄：xml tag <relation></relation>; json檔 .divisions[i].sutras[i].relation

第十二欄：xml tag <debate></debate>; json檔 .divisions[i].sutras[i].debate

![2](https://cloud.githubusercontent.com/assets/13195099/11989974/da401e80-aa41-11e5-9dec-f95f3e698bfd.jpg)

**Comment by kmsheng** [comment]
will be fixed in v1.0.30

**Comment by chiehan1** [comment]
Test ok!!
Thank you!!
