### ISSUE TITLE
刪減後的進階搜尋第一欄 對應的 biography.json檔項目

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#34]
刪減欄位後的進階搜尋第一欄要match的biography.json的四個項目分別是

 .divisions[i].sutras[i].tname
 .divisions[i].sutras[i].aname
 .divisions[i].sutras[i].sname
 .divisions[i].sutras[i].cname

搜尋方式採用 **OR**  

![default](https://cloud.githubusercontent.com/assets/13195099/11990011/6109e0ea-aa42-11e5-80ee-6c49be186a7a.jpg)

**Comment by chiehan1** [comment]
補充一下
這裡的搜尋方式採用 **OR**  指的是第一欄的關鍵字 match到下面四個項目任一個都可以
.divisions[i].sutras[i].tname
.divisions[i].sutras[i].aname
.divisions[i].sutras[i].sname
.divisions[i].sutras[i].cname

但整個進階搜尋的結果仍然是採用 **AND**

**Comment by kmsheng** [comment]
@chiehan1 第一欄是 tname, 那如果下面的 aname, sname, cname 也有填值得話是覆蓋嗎 ?

**Comment by kmsheng** [comment]
@chiehan1 還是說只有下面四個項目為空的時候才把 tname 代入 ?

**Comment by chiehan1** [comment]
整體的進階搜尋規則不變，就是 AND
只是其他欄位match的範圍是一項
第一欄match的範圍是四項合併

一部經可能同時有 藏文經名、別名、梵文經名、中文經名
tname 是藏文經名 aname 是別名 sname 是梵文經名 cname 就是中文經名

這一欄本來是去 match tname 的值，但是後來因為欄位太多，想縮減欄位
所以把下面的 aname sname cname 和第一欄的 tname 併在一起
剛好 tname 那一欄本來的藏文只寫 མདོ་མིང་། ，就是經名
這時就可以想成是那一欄是 中文經名 + 別名 + 梵文經名 + 中文經名，都是經名，都是同一欄

等於是把biography.json的 tname aname sname cname的值併在一起
可以想成這一欄key in 的關鍵字就去match 這個併在一起的值
所以就變成如果那一欄填的值 match 到 tname 或 aname 或 sname 或 cname 都可以

可以說是這四項要聯集成一項，就是第一欄如果有輸入關鍵字，去match的範圍
然後包括第一欄，所有有輸入關鍵字的欄位再去取交集，每一欄關鍵字都match到，才可以

如有問題或是寫得不清楚，請再comment或skype或寄信都可以，辛苦了，感謝!!

**Comment by kmsheng** [comment]
fixed in v1.0.37
