### ISSUE TITLE
希望螢幕icon下方的ADARSHA改成Adarsha

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#35]
希望螢幕icon下方的ADARSHA(黃色框所示)改成Adarsha，只有第一個字母A大寫

![52 1](https://cloud.githubusercontent.com/assets/13195099/11991478/d62f57d4-aa55-11e5-9374-b0a7bc165577.PNG)

**Comment by kmsheng** [comment]
will be fixed in v1.0.30

**Comment by chiehan1** [comment]
進版頁的ADARSHA iOS希望不要一起改成Adarsha ，只有螢幕的icon改就可以了，感謝

**Comment by chiehan1** [comment]
Test ok in v1.0.35
