### ISSUE TITLE
內文閱覽模式 執行搜尋後 經文在進行藏文和 wylie 羅馬轉寫轉換後 也需要 highlight 符合的字

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#38]
內文閱覽模式，執行搜尋後，經文在進行藏文和wylie羅馬轉寫轉換後， 
也需要highlight符合的藏文字或Wylie羅馬轉寫的字。

**Comment by kmsheng** [comment]
@yapcheahshen 請問 kse.search 有實作這個嗎 ?

**Comment by kmsheng** [comment]
@chiehan1 wylie highlight 顯示是不是也要依照 https://github.com/karmapa/AdarshaIos/wiki/%E5%85%A8%E6%96%87%E6%AA%A2%E7%B4%A2-Wildcard-%E6%90%9C%E5%B0%8B%E8%A6%8F%E5%89%87

**Comment by chiehan1** [comment]
理論上是的

**Comment by yapcheahshen** [comment]
在ksa.renderHits 的callback 之內轉成wylie

2015-12-31 3:06 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
@chiehan1 已套用到 v1.0.45

**Comment by chiehan1** [comment]
測試ok!!

感謝!!!
