### ISSUE TITLE
更換 App Icon

### ISSUE THREAD

**Issue by kmsheng** [karmapa/AdarshaIos#39]
根據印度那邊的需求, 要將
<img src="https://cloud.githubusercontent.com/assets/880569/11994998/d46da418-aa83-11e5-834a-690f82b86de9.png" width="200" height="200" />
改成
<img src="https://cloud.githubusercontent.com/assets/880569/11995000/dc204904-aa83-11e5-83ab-540ddfca599f.png" width="200" height="200" />

**Comment by kmsheng** [comment]
will be addressed in v1.0.30

**Comment by chiehan1** [comment]
新icon圖的四個角被切掉了，希望能將圖縮小一點，讓四個角不要被icon的外框界限裁掉

**Comment by chiehan1** [comment]
Test ok in v1.0.35
