### ISSUE TITLE
全文檢索一般搜尋結果 pb id 顯示錯誤

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#40]
搜尋 chos rnams gang dag rgyu las byung ba dang

應找到
1.36a
67.95b
114.36b

但結果顯示
1.36a
67.95b
1.36b

已請葉老師更新 ksana-search 到 1.3.2版
請David也更新ksana-search 到 1.3.2版，十分感謝

**Comment by kmsheng** [comment]
@yapcheahshen ksana-search 已更新到 329db65 這個 commit, kdb 也重新下載了, 有底下錯誤
![screen shot 2015-12-25 at 8 00 19 pm](https://cloud.githubusercontent.com/assets/880569/12002725/98d6f07a-ab42-11e5-9a4d-50a0ecb7906d.png)

**Comment by kmsheng** [comment]
![screen shot 2015-12-25 at 8 48 53 pm](https://cloud.githubusercontent.com/assets/880569/12002936/f403cc42-ab48-11e5-8763-11397f411afe.png)

**Comment by kmsheng** [comment]
MD5 (jiangkangyur.kdb) = 4951d112a56a7b99858949e8a4ed525f

**Comment by yapcheahshen** [comment]
這看起來是檔案損毀。
用node.js 開得了嗎？

2015-12-25 20:49 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
@yapcheahshen node.js 可以

**Comment by kmsheng** [comment]
@yapcheahshen 你有上一版的 kdb 嗎? 如果這個短時間內修不好 我不想一直卡在這裡

**Comment by yapcheahshen** [comment]
麻煩了，這是low level 錯誤，請index.ios.bundle 寄給我
如果還看不出來就要到xcode 才有辦法除錯。

另外，你試試 update jiangkangyur repo
以及 ksana-indexer@1.1.5

在mac build jiangkangyur.kdb 試試

2015-12-25 21:06 GMT+08:00 kmsheng notifications@github.com:

**Comment by yapcheahshen** [comment]
http://ya.ksana.tw/kdb/jiangkangyur_11.kdb 上個月build 的

2015-12-25 21:10 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
@yapcheahshen 已嘗試在 mac rebuild 無效, main.jsbundle 已寄出

**Comment by kmsheng** [comment]
問題解決了, 必須要勾選 target
![screen_shot_2015-12-25_at_10_10_49_pm](https://cloud.githubusercontent.com/assets/880569/12003325/86eaacaa-ab54-11e5-8e98-00904641e117.jpg)

**Comment by yapcheahshen** [comment]
對，我之前也踫過類似問題。
所以loadbysignature 的error 可能是開了一個存在，但內容為空的檔案。

2015-12-25 22:12 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
fixed in v1.0.35, please reopen if issue persists
