### ISSUE TITLE
font size , line height not working

### ISSUE THREAD

**Issue by yapcheahshen** [karmapa/AdarshaIos#41]
to repeat the issue:
go to 1.1b  , 
scroll to 1.7a , open setting panel, click on wylie transliteration, nothing happen.
close setting panel, up scroll to 1.3a , wylie is shown along with Tibetan texts.

expected behavior:
all pages must be Tibetan or wylie at any time, not both at the same time.
![img_0999](https://cloud.githubusercontent.com/assets/1085366/12009879/6aa774c8-acc7-11e5-8048-caa6786a0f54.PNG)

**Comment by kmsheng** [comment]
Thanks for reporting this, the fix will be addressed in next release

**Comment by kmsheng** [comment]
fixed in v1.0.35, please reopen if issue persists
