### ISSUE TITLE
全文檢索的 wildcard 搜尋， ios 上無法顯示 node 跑出的結果

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#42]
以下是用 node 跑出的結果，但在ios上顯示不出來
分別用了 ~~'byor.dam~~
~~'khor.2mtsho~~
~~'khor.3smre~~
~~snyam.9bya~~
chos*spyod
brtse*9'dis
共~~6~~2組關鍵字

chos*spyod
q= ཆོས*སྤྱོད
match count 218
[ '1.112b)ཐམས་ཅ...ཏེ། །【ཆོས་སྤྱོད་】ཞི་དུ...་འཆི་',
  '2.46a)གང་། ...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】གྱུར་...་ས་ར་',
  '2.53a)པོའི་...ག་དང་【ཆོས་སྤྱོད་】དེ་སྦ...བསོད་',
  '2.197a)པོ་སྔ...ག་ཏུ་【ཆོས་སྤྱོད་】ཅིང་ས...ག་ཏུ་【ཆོས་སྤྱོད་】ཅིང་ཚ...ུ་རྩ་',
  '2.257a)འབྱོར...ང་གི་【ཆོས་སྤྱོད་】ཅིག  ...གྱུར།',
  '4.4b)བསྐྱེ...དང་། 【ཆོས་སྤྱོད་】པ་ལེག...དེའི་',
  '5.238a)བསྲུང...དང་། 【ཆོས་བཞིན་སྤྱོད་】པ་དེ་...་དགེ་',
  '6.94a)སྨྲས།...ང་གི་【ཆོས་སྤྱོད་】ཅིག །...ར་རབ་',
  '8.98b)ལས་ཐར...ུར་པ་【ཆོས་སྤྱོད་】བྱེད་...ང་དུ་',
  '9.87b)གའི་བ...་གཞི་【ཆོས་སྤྱོད་】པར་བྱ...འོ། །',
  '10.46a)སློང་...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】པར་ཤོ...སྨྲས་',
  '10.160b)དེ་ལྟ...ཡིན། 【ཆོས་སྤྱོད་】པ་མ་ཡ...་ཤིང་',
  '10.188b)པོ་ལ་...བྱ། །【ཆོས་སྤྱོད་】འཇིག་...ན་ནུ་',
  '11.50b)སུ་བཅ...པོ། །【ཆོས་སྤྱོད་】ཐུབ་པ...ག་པར་',
  '11.120a)འདུག་...་ཤིང་【ཆོས་ལ་སྤྱོད་】དོ་ཞེ...ེ་དང་',
  '11.130b)ཁྱེའུ...་པའི་【ཆོས་སྤྱོད་】པ་འདི...ཤིག །',
  '13.321a)འདིར་...ལ་དང་【ཆོས་སྤྱོད་】རྣམ་བ...ྱལ་བ་',
  '13.335b)གསུངས...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】པར་ཤོ...་བ། །',
  '13.337b)མཛད་ཀ...ན་དུ་【ཆོས་ལ་སྤྱོད་】གྱུར་...ཏེ། །',
  '20.119a)བདག་ཏ...་པའི་【ཆོས་རྣམས་སྤྱོད་】པའི་ཚ...ྱིགས།',
  '26.157a)ལྷ་ཚེ...་བའི་【ཆོས་མྱི་སྤྱོད་】པའི་ན...རྗོད་',
  '26.260b)གལ་ཏེ...་བའི་【ཆོས་ལ་སྤྱོད་】པ་མཐོ...ན་དུ་',
  '32.192b)འདྲ་བ...་བའི་【ཆོས་ལ་སྤྱོད་】པ་མཐོ...ལ་དང་',
  '35.240b)ལྷ་མ་...་པའི་【ཆོས་ལ་སྤྱོད་】ན། རབ...མཐོང་',
  '36.170a)ཅི་ཕྱ...ིར། །【ཆོས་གང་སྤྱོད་】པ་དེ་...ུབ་ལ་',
  '37.298a)དགྲ་བ...པོའི་【ཆོས་ལ་སྤྱོད་】དམ། འ...་པའི་【ཆོས་ལ་སྤྱོད་】པ་ཡིན...་པའི་【ཆོས་ལ་སྤྱོད་】པ་ཡིན...་དང་།',
  '38.45a)འཇུག་... ལ་ལ་【ཆོས་སྤྱོད་】པ་དང་...སྤངས་',
  '38.257b)དུ་ཞེ...་ཀྱི་【ཆོས་ཉིད་སྤྱོད་\n】ཀྱང་ཆ...འོ། །',
  '39.2b)བརྟོན...ིར། །【ཆོས་གང་སྤྱོད་】པ་དེ་...ཏེ། །',
  '39.284b)དང་ནི...ིན་པ་【ཆོས་ཀྱི་སྤྱོད་】པ་དང་...་མདོ།',
  '40.3a)ཅད་ཀྱ...་པའི་【ཆོས་ལ་སྤྱོད་】ཀྱང་ཡ...་ཀྱི་【ཆོས་ལ་སྤྱོད་】ཀྱང་ཐ...གསོལ།',
  '41.14b)ཡིན་ལ...དོ། །【ཆོས་སྤྱོད་】པ་མེད...དེའང་',
  '41.94a)ནས། ན...་བའི་【ཆོས་སྤྱོད་】པ་ཐམས...ི་ནི་',
  '41.115b)རྣམས་...ི་བུ་【ཆོས་སྤྱོད་】ཀྱིས་...ླུའི་',
  '41.146b)བྱའི་...ོན་ན་【ཆོས་ནི་སྤྱོད་】པར་འག...ཤི་བ་',
  '41.199a)ཁྱོད་...རྣམས་【ཆོས་སྤྱོད་】རྒྱུན...ེ་དག་',
  '41.219a)འཕྲུལ...དང་། 【ཆོས་སྤྱོད་】དང་། ...་མོས་',
  '42.136a)ཅན། །...་བའི་【ཆོས་བཙལ་སྤྱོད་】པ་སྤྱ...སྨོན་',
  '42.300a)འབྱུང...་པའི་【ཆོས་ལ་སྤྱོད། །】དེ་བཞ...་མཚན་',
  '43.56a)འདས་ད... །དམ་【ཆོས་སྤྱོད་】ལ་རྟག...འཇོག་',
  '43.125b)པར་བྱ...ང་། །【ཆོས་ལ་སྤྱོད་】པ་མ་ས...ེད། །',
  '43.202b)དེར་མ...་པའི་【ཆོས་ཀྱང་སྤྱོད་】པར་འག...ང་། །',
  '43.211b)དེ་ལས...་གིས་【ཆོས་ནི་སྤྱོད་】པ་ན། ...ག་ཏུ་【ཆོས་མི་སྤྱོད། །】དེ་བས...ས་ཅན་【ཆོས་སྤྱོད་】པ་ཞིག...་དེས་',
  '44.61b)སྟོན་...་བའི་【ཆོས་ལ་སྤྱོད་】པའི་ག...རྒྱལ་',
  '44.173b)ཙམ་ནི...ང་ཟག་【ཆོས་སུ་སྤྱོད་】པར་ཡང...རླབས་',
  '47.63b)ཀྱི་བ...པོའི་【ཆོས་སྤྱོད་】དོ། །...ེད་པ་',
  '47.186a)ཐོབ་པ...་བའི་【ཆོས་ལ་སྤྱོད་】པ་མེད...་དང་།',
  '47.196b)ཡིན་པ...་བའི་【ཆོས་སྤྱོད་】པར་འག...རོ། །',
  '47.255b)བུ་གཞ...་ཀྱི་【ཆོས་སྤྱོད་】པའི་\n...་དཔའ་',
  '47.351b)ཞིང་ད...པ་དང་【ཆོས་སྤྱོད་】པ་དང་...་སྟེ།',
  '48.13b)རྒྱ་མ...བའི་\n【ཆོས་སྤྱོད་】པ་ལ་མ...འོ། །',
  '48.82a)བུ་རྣ...་བའི་【ཆོས་སྤྱོད་】པ་རྣམ...གས་པ་',
  '48.199b)དེ་བཞ...ག་གི་【ཆོས་སྤྱོད་】པ་དང་...ས་ཏེ་',
  '48.303b)མྱ་ངན...་བའི་【ཆོས་ལ་སྤྱོད་】པར་མི...་པའི་',
  '48.331a)སྣང་བ...་པའི་【ཆོས་སྤྱོད་】པས་སེ...ལ་པོ་',
  '49.37a)འདུ་ཤ...དང་། 【ཆོས་སྤྱོད་】པར་འག...ས་སམ།',
  '49.78b)ནས་རྒ...་རམ། 【ཆོས་སྤྱོད་】པའི་ཕ...བ་ནས་',
  '49.177a)ཆེན་པ...་ཀྱི་【ཆོས་སྤྱོད་】པ་ཞིག...སློང་',
  '49.191a)བྱ་སྟ...་པའི་【ཆོས་སྤྱོད་】པ་ལ་ཡ...། གང་',
  '49.244b)ནས། ས...ད་དུ་【ཆོས་སྤྱོད་】པ། །ད...ྟོབས་',
  '50.17b)སུ་དག...ང་ནས་【ཆོས་སྤྱོད་】པ། །ད...ཁྱིམ་',
  '50.45b)མིན། ...རྒྱས་【ཆོས་སྤྱོད་】པ། །',
  '50.297a)འཛིན་...ས་ཅད་【ཆོས་སྤྱོད་】པ་དང་...གྱུར་',
  '51.33b)དེ་དག...་པའི་【ཆོས་ལ་སྤྱོད་】པ། ལུ...ས་མང་',
  '51.54a)ཁྲིམས...་ཀྱང་【ཆོས་ལ་སྤྱོད་】ཅིག་ད...་ཅིང་',
  '51.75b)ནི་དུ...ནི། །【ཆོས་ཀྱི་སྤྱོད་】ཡུལ་ག...་དང་།',
  '51.134b)བདེན་...་པའི་【ཆོས་སྤྱོད་】པ་ནི་',
  '51.137b)འདྲེས...ིས་ན་【ཆོས་སྤྱོད་】དོ་ཅོ...ང་མི་',
  '51.164a)པ་དཀོ...བ་ནི་【ཆོས་སྤྱོད་】པ། །ས...དུའི་',
  '51.202b)རྣམས་...ར་དུ་【ཆོས་ལ་སྤྱོད་】པའི་ས...་བའི་【ཆོས་སྤྱོད་】པ་སྟོ...་བའི་【ཆོས་སྤྱོད་】དོ། །...་དང་།',
  '51.232a)འདི་ན...ད་ནི་【ཆོས་ཀྱི་སྤྱོད་】པ་སྤང...གསུང་',
  '51.236b)བཏུལ་... །དམ་【ཆོས་སྤྱོད་】པ་འཇི...བཞིན་',
  '52.24a)བའི་ད...པོའི་【ཆོས་སྤྱོད་】པ་དང་...དཔའི་',
  '52.41a)བརྩོན...་མེད་【ཆོས་ལ་སྤྱོད་】པར་འག...ོབ། །',
  '52.258a)པའི་ན...ང་། \n【ཆོས་སྤྱོད་】པས་བས...སོ། །',
  '53.12a)པ་དང་...ཕྱིར་【ཆོས་ལ་སྤྱོད་】པ་དང་...་ལུས་',
  '53.58b)ལྡན། ...་པའི་【ཆོས་སྤྱོད་】པ། །\n...་ལྡན་',
  '53.108b)དེ་དག...ང་དུ་【ཆོས་སྤྱོད་】ཅིག །...། གང་',
  '53.193b)པ་དམན...་པའི་【】ཆོས་ལ་',
  '53.235a)ཐམས་ཅ...ཡིན། 【ཆོས་སྤྱོད་】པས་བས...གཅོད་',
  '53.351a)དེ་དག...ང་དམ་【ཆོས་སྤྱོད་】པ་དང་...ིན། །【ཆོས་སྤྱོད་】པ་དང་...ད་དང་【ཆོས་རྣམས་སྤྱོད་】པ་དང་...ེད། །',
  '54.12a)གཞན་ཡ...་བའི་【ཆོས་སྤྱོད་】པ་ཐམས...ྣཾ་པ་',
  '54.98b)དེ་དང...ར་ནི་【ཆོས་ལ་སྤྱོད། །】བདག་མ...ྫོགས་',
  '54.211a)ཇི་འད...་པའི་【ཆོས་སྤྱོད་】པའི་ས...་དང་།',
  '54.266a)བྱང་ཆ...དང་། 【ཆོས་སྤྱོད་】ཡུལ་བ...དང་། 【ཆོས་སྤྱོད་】པ་དང་...དང་། 【ཆོས་ཀྱི་སྤྱོད་】ལམ་དང...སྟེ། 【ཆོས་སྤྱོད་】པ་རྣམ...་དང་།',
  '54.311a)ཡང་དག...་མེད་【ཆོས་ལ་སྤྱོད་】པར་བྱ...་ཆོས་',
  '55.8a)ཚད་མེ...་པའི་【ཆོས་ཀྱི་སྤྱོད་】ཡུལ་ཚ...ཀྱིས་',
  '55.292a)བྱང་ཆ...དེ་ལ་【ཆོས་སྤྱོད་】ཇི་ལྟ...རྣམས་',
  '56.292b)རིགས་...་པའི་【ཆོས་ལ་སྤྱོད། །】ཤེས་བ...་ཁྲག་',
  '57.14b)འདོད་...ག་ནི་【ཆོས་སྤྱོད་】པ་ལ་ག...་ཀྱང་【ཆོས་སྤྱོད་】པ་ལ་ད...དེ་ལ་【ཆོས་སྤྱོད་】པ་ནི་...རལ་བ་',
  '57.80a)དཔའི་...། དེ་【ཆོས་ཀྱི་སྤྱོད་】པ་ཆུད...་ཀྱང་【ཆོས་ཀྱི་སྤྱོད་】པ་ཆུད...་གྱི་',
  '57.104a)རྣམས་... །དག་【ཆོས་སྤྱོད་】ཡུལ་ཅ...་ཤེས་',
  '57.186b)འདས་ཀ...་པའི་【ཆོས་ལ་སྤྱོད་】དེ། ཇ...་པ། །',
  '58.52a)ལ་མི་...་པའི་【ཆོས་སྤྱོད་】ཅིང་ཡ...ཕྱུར་',
  '58.93b)པས་ནི...ོ་། །【ཆོས་སྤྱོད་】པ་ནི་...ིན། །【ཆོས་སྤྱོད་】པ་ཡི་...ཏེ། །【ཆོས་སྤྱོད་】པ་ནི་...།  །།',
  '58.143b)འཛིན་...ཕྱིར་【ཆོས་སྤྱོད་】རབ་ཏུ...་བ་ལ་',
  '58.235b)གང་དུ...གྱིས་【ཆོས་སྤྱོད་】པ་ལ་ལ...་ལྡན་',
  '58.292a)དེ་དག...་དཀའ་【ཆོས་སྤྱོད་】པས། །...་ལུང་',
  '58.300a)དག་གི...ཞིང་\n【ཆོས་སྤྱོད་】ལ་མཐོ...མ་ལས་',
  '58.318b)ན་ཀླུ...་ཀྱི་【ཆོས་རྣམས་སྤྱོད་\n】པར་བག...མཆིས་',
  '59.171b)པའི་ས...་པའི་【ཆོས་ལ་སྤྱོད་】པར་མཛ...ད་པར་',
  '59.228a)སུ་འག...་ཅིང་【ཆོས་སྤྱོད་】པར་འག...རོ། །',
  '60.22b)སྨོན་...ས་པ། 【ཆོས་སྤྱོད་】པ་ལ་ད...་རིན་',
  '60.138a)ཏན་ལ་...ཇུག །【ཆོས་ལ་སྤྱོད་】པར་ཐབ...ད་པར་',
  '60.150b)པ་ལགས...་བའི་【ཆོས་སྤྱོད་】པས་\nན...ཞེ་ན།',
  '60.212b)ཙམ་དུ...་བའི་【ཆོས་སྤྱོད་】པ་ལྟ་...ཤིག །',
  '61.5a)ལ་དྲི...ོ་། །【ཆོས་སྤྱོད་】པ་རྣམ...གཅིག་',
  '61.64b)བྱང་ཆ...་ཀྱང་【ཆོས་སྤྱོད་】པ་སྟེ...དོ། །',
  '62.53a)ཕྱག་འ...་མེད་【ཆོས་ཀྱི་སྤྱོད་】ཡུལ་ལ...ལོ། །',
  '62.335b)རླན་པ...ཁམས་\n【ཆོས་སྤྱོད་】ཅེས་བ...གས་པ་',
  '63.73b)ཡལ་བར...ག་གི་【ཆོས་སྤྱོད་】པ། ཡང...་ཆུབ་',
  '63.126a)གང་ཞི...ོན། །【ཆོས་ཀྱི་སྤྱོད་】ཡུལ་ད...ང་། །',
  '64.78b)ལེགས་...ོས། །【ཆོས་སྤྱོད་】བདེ་བ...མས་པ་',
  '65.22a)སྨོན་...ང་ཕན་【ཆོས་ལ་སྤྱོད། །】གང་གི...ྐྱེས་',
  '66.14a)སྐྱོན...་བའི་【ཆོས་སྤྱོད་】པ། །ས...འ་བར་',
  '67.27b)ཁང་པར...དང་། 【ཆོས་སྤྱོད་】པ་ལེག...། ཡང་',
  '67.135a)དེ་ནས...་གཏན་【ཆོས་སྤྱོད་】ཟས་མཆ...རྒྱས་',
  '67.156b)འཆི་བ...་པའི་【】ཆོས་ནི་',
  '67.173b)གྲུབ་...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】གྱུར་...མས་པ།',
  '67.197b)ལྷ་དང...་པའི་【ཆོས་སྤྱོད་】པ་སྟེ...་པའི་',
  '67.219a)དགའ་བ...གཉིས་【ཆོས་\nསྤྱོད་】མ་ཡིན...ནས། །',
  '67.228a)གང་དག...ས་སུ་【ཆོས་ལ་སྤྱོད་】པ་དང་...ང་། །',
  '68.94b)དེ་ནས...ན་པར་【ཆོས་སྤྱོད་】པའི། ...ང་གི་',
  '69.165b)འདི་ས...་པའི་【ཆོས་སྤྱོད་】པར་དད...ྱིབས་',
  '69.230a)བཀའ་ད...ད་ནི་【ཆོས་སྤྱོད་】པ་ཡིན...་སྟེ་',
  '69.312b)སུམ་བ...ྙན་ལ་【ཆོས་སྤྱོད་】པའི་ཚ... །ཚལ་',
  '70.118a)པ་བཙལ...ཏུ། །【ཆོས་སྤྱོད་】བདེ་ལ...ག་ནས་',
  '71.102b)པས་ནི...་གྱི་【ཆོས་ལ་སྤྱོད་】པའི་ཚ...རྒྱད་',
  '71.127a)མང་པོ...་གྱི་【ཆོས་ལ་སྤྱོད་】པའི་ཚ...ིན་པ་',
  '71.152b)མགོ་བ...ྙན་ལ་【ཆོས་སྤྱོད་】པའི་ཚ...ྲས་པ།',
  '71.190a)གཞན་ཡ...་པའི་【ཆོས་ལ་སྤྱོད་】པའི་ཚ...འོ། །',
  '71.225a)མིའི་...ས་ཅན་【ཆོས་སྤྱོད་】པ་རྣམ...་པའི་【ཆོས་སྤྱོད་】པ་ཡང་...ཕྲོག་',
  '71.237a)རྟེན་...འདིར་【ཆོས་ཀྱི་\nསྤྱོད་】པ་ཡོང...གས་པ་',
  '71.296b)བདེའི...ལ་དང་【ཆོས་སྤྱོད་】རྣམ་བ...སྐབས་',
  '72.19b)སྣང་བ...་བའི་【ཆོས་ལ་སྤྱོད་】པའི་ད...ྲོ་བ་',
  '72.197b)མ་མངོ...་པའི་【ཆོས་ཅན་སྤྱོད་】ཡུལ་འ...རུང་།',
  '72.225a)མཐོང་...ེད། །【ཆོས་དབྱིངས་སྤྱོད་】ཡུལ་ཕ...གས་ན་',
  '72.244a)གཤིན་...་ཀྱི་【ཆོས་ཀྱི་སྤྱོད་】པ་ཐམས...ན་པོ་',
  '72.249a)སེམས་...ང་། །【ཆོས་ཀྱིས་སྤྱོད་】པར་འཇ...་པ། །',
  '73.81b)སངས་ར...པོའི་【ཆོས་ལ་སྤྱོད་】པའི་ཚ...་པའམ།',
  '73.140b)རྟེན་...་བའི་【ཆོས་སྤྱོད་】པ་ལ་ར...་མའི་',
  '74.32a)པའི་ཆ...་ཞིང་【ཆོས་ཀྱི་སྤྱོད་】པའི་ཕ...་ཆུད་',
  '74.111b)དང་ཚད...རྟེན་【ཆོས་སྤྱོད་】ཀྱང་།...བ་དན་',
  '75.23b)ཚུལ་ག...ས་ནས་【ཆོས་ཀྱི་སྤྱོད་】པ་རབ་...སམ་པ་',
  '75.53a)གཞན་མ...་ཀྱི་【ཆོས་ཀྱི་སྤྱོད་】པས་མཐ...ང་དང་',
  '75.109b)བག་ཡོ...་ཞིང་【ཆོས་ལ་སྤྱོད་】པར་འག...རྒྱས་',
  '76.37b)ཡང་དམ...ར་ནི་【ཆོས་དང་སྤྱོད་】པ་སྟོ...ྒྱུར་',
  '76.79a)རེ་རེ...ད་པར་【ཆོས་ལ་སྤྱོད་】པ། ཆོ...་པའི་',
  '77.27b)སྟོན་...་པའི་【ཆོས་ཀྱི་སྤྱོད་】ཡུལ་ལ...་ཀྱི་',
  '78.14a)སྐྱེའ...་པའི་【ཆོས་སྤྱོད་】དོ། །...་ཆུབ་',
  '80.307a)ནི་ཆོ...ེ་བོ་【ཆོས་སྤྱོད་】འདི་ད...ོལ། །',
  '81.12b)འཆར་ཀ...ྲས། །【ཆོས་ལེགས་སྤྱོད་】ཅིང་ད...མ་མེ་',
  '81.266a)འགྱུར...་བའི་【ཆོས་སྤྱོད་】ན། །བ...འཕགས་',
  '81.293a)བསྔལ་...ཀྱིས་【ཆོས་སྤྱོད་】པ་དང་...ོལ་པ་',
  '82.11a)འགྲོག...་ཀྱི་【ཆོས་སྤྱོད་】པའི་ས...་ལྡན་',
  '82.72a)རྣམས་...ད་པས་【ཆོས་སྤྱོད་】པ་ནི་...ར་མེ་',
  '82.207b)བསྔལ་...ེས་པ་【ཆོས་སྤྱོད་】པ། །བ...ི་ཟླ་',
  '82.227a)ལས་ཀྱ...ྟན་ལ་【ཆོས་སྤྱོད་】ཅིག །...་དགའ་',
  '82.233b)འཆལ་པ...བུའི་【ཆོས་སྤྱོད་】པ། གན...་མེད་',
  '83.27b)སེང་ག...་ལྟར་【ཆོས་སྤྱོད་】འགྱུར...་\nཔས་【ཆོས་སྤྱོད་】འགྱུར...གས། །',
  '83.108a)ཅིང་།...ེད། །【ཆོས་སྤྱོད་】མངོན་...ར་ཞན་',
  '83.137a)དཔའི་...་དཔའ་【ཆོས་སྤྱོད་】པ་དང་...་ཚུལ་',
  '83.175a)ལོག་པ...ང་གི་【ཆོས་དང་། སྤྱོད་】ལམ་ཐམ...་པའི་',
  '83.230a)བརྒྱ་...དང་། 【ཆོས་ཀྱི་སྤྱོད་】པས་སེ...་དང་།',
  '84.155b)རིགས་...་ཡུལ་【ཆོས་སྤྱོད་】པས་གྲ...་ཐུབ་',
  '86.248a)དེ་ནས...་བའི་【ཆོས་སྤྱོད་】པའམ། ...མ་དུ་',
  '87.166b)རོ་ཧི...ུལ་ལ་【ཆོས་ནི་སྤྱོད་】པ་དང་...་ཁྲལ་',
  '87.263b)གསེར་...་ཞིང་【ཆོས་སྤྱོད་】པ། །\n...མ་པར་',
  '88.308a)བདེ་བ...་བའི་【ཆོས་སྤྱོད་】པ། རྣ...རྣམས་',
  '88.344a)པར་དག...་བའི་【ཆོས་ལ་སྤྱོད་】པ། རྣ...ྡན་པ་',
  '90.151a)༄༅།  ...ྲོ་བ་【ཆོས་བཞིན་སྤྱོད་】པ་ཡི།...འ་དང་',
  '91.163a)མདུན་...་པ། །【ཆོས་མིན་\nསྤྱོད་】ཅིང་བ...་འཕང་',
  '94.258b)པར་རྫ...་བའི་【ཆོས་སྤྱོད་】པར་གྱ...་འཆི་',
  '95.11b)ཉིན་ད...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】གྱུར་...ཅིག །',
  '95.82b)ཆེན་པ...ཀྱིས་【ཆོས་སྤྱོད་】པ་དང་...་ཡིན་',
  '95.92a)ཀྱི་བ...ྟེ། །【ཆོས་དོན་\nསྤྱོད་】པ་དེ་...རྒྱད་',
  '95.100b)དེའི་...དང་། 【ཆོས་སྤྱོད་】པ་ཆུང...ཚན་མ་',
  '95.125b)ས་ཡི་...་འཆལ་【ཆོས་མིན་སྤྱོད་】པ་དང་...་ལ། །',
  '95.276b)ནི་ལོ...རྟེན་【ཆོས་ཀྱིས་སྤྱོད་】པར་ལྡ...ོད། །【ཆོས་ལ་སྤྱོད་】ཅིང་\n...་ལུས་',
  '96.46b)འདི་ས...་པའི་【ཆོས་སྤྱོད་】པས་བྲ...ན་དུ་',
  '96.75b)སི་དྷྱ...་བའི་【ཆོས་ཀྱི་སྤྱོད་】པ་ཞེས...ི་བུ་',
  '96.83a)ཁྱབ་མ...ེད། །【ཆོས་ལ་\nསྤྱོད་】པས་སྐ...ག །ས་',
  '96.85a)འབྱོར...་ཀྱི་【ཆོས་སྤྱོད་】པ་བསྒ...ྐྱེན་',
  '96.116b)མཚན་བ...་ལྟར་【ཆོས་བཞིན་སྤྱོད་】ནུས་ན...ེད། །',
  '96.134a)གཅིག་...ས་ཅད་【ཆོས་མིན་སྤྱོད་】པར་འག...ུར། །【ཆོས་མིན་\nསྤྱོད་】པ་མཐོ...།དགེ་【ཆོས་སྤྱོད་】པའི་མ...ས་ཅད་',
  '96.189b)ཡོངས་...་པའི་【ཆོས་སྤྱོད་】ཅིང་།...་ཞིང་',
  '96.210a)བརྒྱ་...བཞིན་【ཆོས་བཞིན་སྤྱོད་】པར་འག...ྲན་ལ་',
  '96.274a)བསྲེག...་པའི་【ཆོས་མི་སྤྱོད་】ན། ཡུ...བསྟན་',
  '97.77b)རྒྱས།...བ་དང་【ཆོས་སྤྱོད་】པ། །ས...རྣམས་',
  '98.125b)བརྫུན...་ཞིང་【ཆོས་སྤྱོད་】མཁས། ...གསེར་',
  '98.152a)བཟླས་...ྟེ། །【ཆོས་ཀྱི་སྤྱོད་】ཡུལ་ག...ཁྱོད་',
  '98.170a)ཀྱི་ན...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】གྱུར་...རྣཾས་',
  '99.239a)དགེ་བ...རོ། །【ཆོས་མི་སྤྱོད་】པ་ཡང་【ཆོས་སྤྱོད་】པ་ཆེན...རོ། །',
  '101.144a)དེ་ལ་...ཇོམས་【ཆོས་ལེགས་སྤྱོད། །\n】བཅོམ་...སྙེན་',
  '101.147b)རྣམས་...ང་གི་【ཆོས་སྤྱོད་】ཀྱང་ར...་པ་ལ་',
  '101.252a)དགར་འ...བཙུན་【ཆོས་སྤྱོད་】དད་པ་...ན་པར་',
  '101.330b)སེམས་...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】པར་ཤོ...་ལ། །',
  '101.333b)ཐམས་ཅ...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】གྱུར་...ུམ་ལ་',
  '101.343b)ཐུགས་...ལ་དང་【ཆོས་སྤྱོད་】རྣམ་བ...ར་ཡང་',
  '102.34a)བྱིས་...ས་པས་【ཆོས་སྤྱོད་】རྟོག་...ྟན། །',
  '102.188a)བདག་ཉ...་པའི་【ཆོས་སྤྱོད་】ཅིང། ...་ན། །',
  '102.252a)སོགས་...ེས་ན་【ཆོས་ལ་སྤྱོད་】པ་ཡི།...ང་བར་',
  '102.343b)བྱུང་...ོས་ལ་【ཆོས་སུ་སྤྱོད་】ཅིང་ན...་སེང་',
  '103.47b)རྒྱལ་...ས་པས་【ཆོས་འདི་སྤྱོད། །】སྐད་ཅ...འི། །',
  '103.49a)མི་ཤེ...་པའི་【ཆོས་སྤྱོད་】ཅིང་།...བཀུར་',
  '103.76a)གཤོགས...རྒྱལ་【ཆོས་ལོངས་སྤྱོད་】བྱ། །...་དག །',
  '103.186a)ཡང་ན་...་བའི་【ཆོས་སྤྱོད་】འདས། ...་མཉམ་',
  '103.306b)ཕྱི་ན...་བའི་【ཆོས་ལ་སྤྱོད་】ཀྱང་ལ...པ་ནི་',
  '104.85a)རང་གི...་ཆགས་【ཆོས་ཀུན་སྤྱོད་】པ་ཡི།...་པོར་',
  '106.40b)དང་དུ...་ཀྱི་【ཆོས་སྤྱོད་】གང་ཡི...ྨན་པ་',
  '106.116b)བྱང་ཆ...ྟེ། །【ཆོས་ཀྱི་སྤྱོད་】ཡུལ་ག...ེན། །',
  '107.37a)དེས་ན...ལེགས་【ཆོས་སྤྱོད། །】བཅོམ་...ལྟ་བ་',
  '107.48b)རཀྵ་ས...ང་གི་【ཆོས་སྤྱོད་】ཀྱང་ར...ཉི་མ་',
  '107.194a)་བ་དེ...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】གྱུར་...ྒྱུན་',
  '107.212b)ཆུང་བ...་པའི་【ཆོས་མི་སྤྱོད་】པས་ནད...ཛུགས་',
  '107.233b)འཁོར་...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】གྱུར་...རྒྱས་',
  '107.243a)ཕྱག་འ...ན་དུ་【ཆོས་ཀྱང་སྤྱོད་】པར་ཤོ...གས། །',
  '114.2a)༄།  ཛ...དེ། །【ཆོས་གནས་སྤྱོད་】པ་ཡོང...ཤིག །' ]

brtse*9'dis
q= བརྩེ*9འདིས
match count 2
[ '67.139a)དགེ་ས...སྙིང་【བརྩེ་བ་འདིས་】ཁྱེད་...ུར་བ་',
  '114.2b)འཁོར་...་ལ། །【བརྩེ་བའི་ཐུགས་རྗེས་སྔོན་ཚེ་བདག་གི་སྟོན་པ་འདིས། །】ཤཱཀྱ་...བར། །' ]

**Comment by kmsheng** [comment]
@chiehan1 測試程式也可以放出來看一下嗎 ? 可以放到 gist

**Comment by chiehan1** [comment]
已可顯示結果
但關鍵字 chos*spyod 在設置 field:"head" 的情況下
應可 show 出 218 項結果
現在只能 show 出前 20 ~ 30 項結果
這點和 https://github.com/karmapa/AdarshaIos/issues/44 重複

**Comment by kmsheng** [comment]
https://gist.github.com/chiehan1/b06f58e9ddac85ea80ea

**Comment by kmsheng** [comment]
https://github.com/karmapa/AdarshaIos/issues/42#issuecomment-168568362 應該在 
https://github.com/karmapa/AdarshaIos/issues/44 解決, 此票先關了
