### ISSUE TITLE
少數字元分離

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#43]
如紅圈中的ཨཱཪྱ
不知是否和字體有關
![default](https://cloud.githubusercontent.com/assets/13195099/12061171/542fd8ca-afba-11e5-8623-8fe0eeb38828.jpg)

**Comment by kmsheng** [comment]
目前先採用 Monlam Uni OuChan1, 網路上翻了一下沒找到授權
http://www.tibetanfont.org/monlam-bodyig-3.html

**Comment by kmsheng** [comment]
@chiehan1 已套用到 v1.0.45

**Comment by chiehan1** [comment]
感謝，但是目錄頁的英文字顯示不正常

**Comment by kmsheng** [comment]
@chiehan1 在 iphone 上能夠符合藏文部首不分家、正常顯示符號字母又有美感的藏文字體似乎不存在，所以必須要有所取捨。

底下是多組字體的測試

Kalasa
![kailasa](https://cloud.githubusercontent.com/assets/880569/12190267/93bcc988-b601-11e5-89bd-beeb52b04734.png)

Kokonor
![kokonor](https://cloud.githubusercontent.com/assets/880569/12190274/a166f662-b601-11e5-8aa5-41e437aca3fc.png)

Monlam Uni OuChan1
![ouchan1](https://cloud.githubusercontent.com/assets/880569/12190279/b482bde4-b601-11e5-9de7-699d7670d8ce.png)

Monlam Uni OuChan2
![monlam_uni_ouchan2](https://cloud.githubusercontent.com/assets/880569/12190285/c00bcfde-b601-11e5-9051-ef7f1bac2061.png)

Monlam Uni OuChan3
![ouchan3](https://cloud.githubusercontent.com/assets/880569/12190287/c3d3694c-b601-11e5-8aae-1412c944e4df.png)

Monlam Uni OuChan4
![ouchan4](https://cloud.githubusercontent.com/assets/880569/12190288/c63a35bc-b601-11e5-8a2d-c0d7815359ea.png)

Monlam Uni OuChan5
![ouchan5](https://cloud.githubusercontent.com/assets/880569/12190292/d57016aa-b601-11e5-946e-31447a54a231.png)

Monlam Uni Dutsa1
![monlam uni dutsa1](https://cloud.githubusercontent.com/assets/880569/12190297/eb6fbae6-b601-11e5-8c63-ba3caff7f4fd.png)

Monlam Uni Dutsa2
![monlam uni dutsa2](https://cloud.githubusercontent.com/assets/880569/12190303/ff6c08d8-b601-11e5-90c5-2cb487b382ac.png)

Monlam Sans Serif
![monlam sans serif](https://cloud.githubusercontent.com/assets/880569/12190308/0e1450fc-b602-11e5-8aab-bbd5efc14036.png)

Monlam Uni Tikrang
![monlam uni tikrang](https://cloud.githubusercontent.com/assets/880569/12190307/0e13baa2-b602-11e5-8741-47a975b46a90.png)

Monlam Uni PayTsik
![monlam uni paytsik](https://cloud.githubusercontent.com/assets/880569/12190309/0e186020-b602-11e5-809b-857b0a5c4e88.png)

Monlam Uni TikTong
![monlam uni tiktong](https://cloud.githubusercontent.com/assets/880569/12190310/0e1b52f8-b602-11e5-87f7-dd54e26a09ac.png)

**Comment by chiehan1** [comment]
@lamalien 法海師您好，在 iphone 上能夠符合藏文部首不分家、正常顯示符號字母又有美感的藏文字體似乎不存在，請問是否將目錄頁首頁的部名梵文轉寫刪去

**Comment by kmsheng** [comment]
@lamalien Hi, 法海師. 請問有看到捷安問的問題嗎 ?

**Comment by lamalien** [comment]
可以拿掉，是否要從biography.json 裡頭去改？

ཆོས་ཀྱི་རྒྱ་མཚོ།

2016-01-14 1:30 GMT+08:00 kmsheng notifications@github.com:

**Comment by chiehan1** [comment]
如果不改原始資料 ( jiangkangyur xml 和 kdb )
請問是否可在顯示樹狀目錄的 部名(第一層目錄 部 的選項 和 第二層目錄上方的灰色 bar )  之前，將拉丁文字取代成空字串

var strings = ["འདུལ་བ།  Vinaya  律部", "ཤེར་ཕྱིན། འབུམ།  Śatasāhasrikāprajñāpāramitā 大般若經", "ཤེར་ཕྱིན། ཉི་ཁྲི། Pañcaviṃśatisāhasrikāprajñāpāramitā  第二般若兩萬五千頌", "ཤེར་ཕྱིན། ཁྲི་བརྒྱད་སྟོང་པ། Aṣṭādaśasāhasrikāprajñāpāramitā  第二大般若經(八萬頌)", "ཤེར་ཕྱིན། ཁྲི་པ། Daśasāhasrikāprajñāpāramitā  第四般若經萬頌一部", "ཤེར་ཕྱིན། བརྒྱད་སྟོང་པ། Aṣṭasāhasrikāprajñāpāramitā  第五般若經八千頌一部", "ཤེར་ཕྱིན། ཤེས་རབ་སྣ་ཚོགས། Prajñāpāramitā 諸般若經部", "མདོ་སྡེ། Sūtram 經部", "ཕལ་པོ་ཆེ། Buddhāvataṃsaka  華嚴部", "དཀོན་བརྩེགས། Ratnakūṭa 寶積部", "རྒྱུད་འབུམ། Tantra 密續部", " དྲི་མེད་འོད། Vimalaprabhā 時輪經疏", "དཀར་ཆག །　大藏經目錄", "པར་བྱང་། 大藏經序"]

var replaceLatin = function(str) {
    return str.replace(/(.+) +[\u0041-\u007a\u00c0-\u02b8\u1e00-\u1ffc]+ +(.+)/, "$1 $2");
}

strings.map(replaceLatin);

results
[ 'འདུལ་བ།  律部',
  'ཤེར་ཕྱིན། འབུམ།  大般若經',
  'ཤེར་ཕྱིན། ཉི་ཁྲི། 第二般若兩萬五千頌',
  'ཤེར་ཕྱིན། ཁྲི་བརྒྱད་སྟོང་པ། 第二大般若經(八萬頌)',
  'ཤེར་ཕྱིན། ཁྲི་པ། 第四般若經萬頌一部',
  'ཤེར་ཕྱིན། བརྒྱད་སྟོང་པ། 第五般若經八千頌一部',
  'ཤེར་ཕྱིན། ཤེས་རབ་སྣ་ཚོགས། 諸般若經部',
  'མདོ་སྡེ། 經部',
  'ཕལ་པོ་ཆེ། 華嚴部',
  'དཀོན་བརྩེགས། 寶積部',
  'རྒྱུད་འབུམ། 密續部',
  ' དྲི་མེད་འོད། 時輪經疏',
  'དཀར་ཆག །　大藏經目錄',
  'པར་བྱང་། 大藏經序' ]

**Comment by kmsheng** [comment]
@chiehan1 可以啊

**Comment by chiehan1** [comment]
了解，那麼就這樣解，感謝!!

**Comment by kmsheng** [comment]
@chiehan1  已在 v1.0.48 (1) 修正

**Comment by chiehan1** [comment]
test ok
thank you
