### ISSUE TITLE
更改黑色 Bar 的背景顏色與字體顏色

### ISSUE THREAD

**Issue by kmsheng** [karmapa/AdarshaIos#49]

**Comment by kmsheng** [comment]
@chiehan1 麻煩請法海師提供背景顏色與字體顏色的色碼

**Comment by chiehan1** [comment]
lamalien 法海師請提供背景顏色和字體顏色的色碼

**Comment by chiehan1** [comment]
@lamalien 法海師請提供背景顏色和字體顏色的色碼

**Comment by chiehan1** [comment]
@lamalien  法海師請提供背景顏色和字體顏色的色碼，感謝

**Comment by chiehan1** [comment]
字體顏色不變

背景顏色色碼為 #1B8C90

**Comment by kmsheng** [comment]
@chiehan1 麻煩 assignee 記得轉給我, 感謝

**Comment by kmsheng** [comment]
![screen shot 2016-01-09 at 2 07 41 pm](https://cloud.githubusercontent.com/assets/880569/12214707/73b7c8de-b6da-11e5-92a5-4723468bc200.png)
@chiehan1 這字體顏色維持這樣不對吧 ? 可讀性太差了

**Comment by kmsheng** [comment]
inactive color react-native 目前不支援從 js 改, 可能要從 objective-c 動手了 https://github.com/facebook/react-native/issues/3083

**Comment by kmsheng** [comment]
@chiehan1 請看看目前的修改是否合適

**Comment by chiehan1** [comment]
測試 ok 
感謝

**Comment by Chaunjie** [comment]
@kmsheng 你现在解决了吗？应该如何更改selected之后的图标和字体颜色

**Comment by kmsheng** [comment]
@xudao520 圖片目前我是用固定顏色, 因為 xcode 改沒效果我就先暫時寫在這裡
https://github.com/kmsheng/react-native/commit/f76b8833f54bed702a89447f0b0cb1562014779f#diff-4be7e7b25008b2fc1a7b598569848ba2R77

字體顏色在這裡設定
https://github.com/karmapa/AdarshaIos/blob/master/ios/AdarshaIos/AppDelegate.m#L44-L50
