### ISSUE TITLE
更改 Keyboard Search View 的提示文字

### ISSUE THREAD

**Issue by kmsheng** [karmapa/AdarshaIos#50]
( 葉老師會再提供 )

**Comment by kmsheng** [comment]
q="byed.bcug";   // byed 和 bcug 中間有一個未知音節
q="byed.2bcug";   // byed 和 bcug 中間有兩個未知音節
q="byed_bcug";  // byed 和 bcug 中間有一個或沒有未知音節
q="byed_3bcug";  // byed 和 bcug 中間有最多3個或沒有未知音節。
q="byed *3 bcug";  // 同上，空白可有可無

**Comment by kmsheng** [comment]
@chiehan1 再麻煩提供要顯示的英文或藏文版本

**Comment by kmsheng** [comment]
@chiehan1 請問這個有下文嗎 ?

**Comment by chiehan1** [comment]
法海師正在翻譯英文

**Comment by kmsheng** [comment]
@lamalien 翻譯好了嗎 ?

**Comment by lamalien** [comment]
正在研究

**Comment by lamalien** [comment]
不是很了解這個提示文字是要寫什麼？

**Comment by kmsheng** [comment]
@lamalien 就是切到鍵盤搜尋, 預設不輸入任何文字的情況下, 搜尋文字框底下會有幾行提示文字..例如 Wildcards 的用法, 上次開會有說要提供藏文或英文官方版本

**Comment by chiehan1** [comment]
Wildcards Search Rule:
. (dot) and _(star) these two wildcards match single unknow syllable.
example: 
search:rdzogs.sangs/ རྫོགས.སངས(1 syllable in between)
result:
-->rdzogs pa’i sangs…../རྫོགས་པའི་སངས་་་་་་
-->rdgogs par sangs…../རྫོགས་པར་སངས་་་་་
example: 
search:rdzogs.2sangs/ རྫོགས.2སངས(2 syllable in between)
result:
-->rdzogs par/_/rdzogs sangs…../རྫོགས་པར། །རྫོགས་སངས་་་་་་
-->rdgogs/_/ngas ni sangs…../རྫོགས། །ངས་ནི་སངས་་་་་
example: 
search:rdzogs_sangs/ རྫོགས_སངས(1 or non syllable in between)
result:
-->rdzogs pa’i sangs…../རྫོགས་པའི་སངས་་་་་་
-->rdgogs sangs…../རྫོགས་སངས་་་་་
example:
search:de_3pa/དེ*3པ(1 or 2 or 3 or non syllable in between)
result:
-->de dag gis smras pa…./དེ་དག་གིས་སྨྲས་པ་་་་་་
-->de la smras pa.../དེ་ལ་སྨྲས་པ་་་་་
-->de gang yin pa…./དེ་གང་ཡིན་པ་་་་་་

**Comment by chiehan1** [comment]
請更新為上面的規則，感謝

**Comment by kmsheng** [comment]
@chiehan1 已更新

**Comment by chiehan1** [comment]
test ok thank you

**Comment by chiehan1** [comment]
請再次更改，感謝
https://docs.google.com/document/d/16_-lN_cNlSyJC3KOASZxwoFmF6gNHhgLLWNOrcDuZ2M/edit?ts=56a68ba6

**Comment by kmsheng** [comment]
@chiehan1 done in v1.0.50 (10)

**Comment by chiehan1** [comment]
測試 ok 
感謝
