### ISSUE TITLE
內文頁的 Icon Buttons 要移到 Search Bar

### ISSUE THREAD

**Issue by kmsheng** [karmapa/AdarshaIos#51]

**Comment by chiehan1** [comment]
補充
原來的 search bar 改為 tool bar。
上面規劃 4 個 buttons。(這裡先列出，由左至右的順序會再補充)
1. 小房子圖示。(原來頁面右上方，經名右邊的小房子)
2. sutra biography 圖示，
取代原來按最上方的經名會 show 出 sutra biogrphy 資料的功能。
圖示的樣式參考 http://ionicons.com/ ，在此網頁中搜尋 file，參考右上的 icon
![biography](https://cloud.githubusercontent.com/assets/13195099/12088336/2ba6a39e-b315-11e5-8331-d84b37836749.JPG)
3. 放大鏡圖示，按了會 show 出 search in sutra 輸入欄。 
4. 設定鍵圖示。(原來頁面右上方，經名右邊的設定鍵)

**Comment by chiehan1** [comment]
由左至右的順序分別是 1.小房子圖示 2.sutra biography 圖示 3.放大鏡圖示 4.設定鍵圖示。

**Comment by kmsheng** [comment]
@chiehan1 fixed in v1.0.45

**Comment by chiehan1** [comment]
測試 ok!!
感謝!!
