### ISSUE TITLE
黑色 bar 最右邊新增第四個版權頁 tab

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#56]
tab 圖案是一個圈圈裡有 i ，如下圖綠色框框裡的圖案
圖案下方的文字是 About
版權頁內容目前還在敲定
![2](https://cloud.githubusercontent.com/assets/13195099/12137490/01240fb2-b48c-11e5-961b-98419accc8e8.JPG)

**Comment by kmsheng** [comment]
@chiehan1 已新增在 v1.0.45 build 2, 版權頁目前文字先放測試的

**Comment by kmsheng** [comment]
@chiehan1 正式版權文稿大概還要多久會出來 ?

**Comment by chiehan1** [comment]
@kmsheng  印度那邊正在討論，這星期會出來

**Comment by chiehan1** [comment]
版權頁背景請用下列連結的圖片，和內文的米黃色背景是一樣的
https://drive.google.com/drive/folders/0B7IngcS_Eo5JQlFHNnprOWtuSzQ

版權頁請先放英文的內容，連結如下
https://drive.google.com/open?id=1-0gsD3W0XwjRnnMSzQO6zMBTIeNdwVIBGcN_8DksLY8

接著再放中文內容，連結如下
https://drive.google.com/open?id=1JGOckMMtVIAVUwvd0ZWblWGMlVKoi_vdQhE_GcMg5t4

內容蠻長的，所以要有滾輪可以捲動
文句排版和標題置中希望能盡量和連結的相同
感謝

**Comment by chiehan1** [comment]
test ok 
thank you
