### ISSUE TITLE
使用內文的 search in sutra 功能時，以當下頁面所在的經為搜尋範圍

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#57]
標紅符合搜尋條件的字，
或使用 previous / next 按鍵，跳到符合搜尋條件的字時，
以使用 search in sutra 功能時，頁面所在的經為範圍。

**Comment by kmsheng** [comment]
@chiehan1 如果超出已載入的資料範圍時, 也要讀取 ( 重新整理 ) 嗎 ? 類似像回到經文第一篇的按鈕 ?

**Comment by chiehan1** [comment]
因為搜尋範圍是一整部經，如果這部經太大，內容就無法一次載入，通常會載入多次，所以當按 pre/next 時，如果下一個字或上一個字是在同一部經裡，但是內容還沒載入，也希望能繼續載入接下來的內容，跳到下一個字或上一個字

**Comment by kmsheng** [comment]
blocked by https://github.com/ksanaforge/ksana-simple-api/issues/4

**Comment by kmsheng** [comment]
@chiehan1 已在 v1.0.50 (3) 修正

**Comment by chiehan1** [comment]
這個 issue 測試 ok! 感謝!!
例如在第一部經搜尋 དཀོན་མཆོག (wylie 轉寫可以輸入 dkon mchog)
會找到所有在第一部經裡的  དཀོན་མཆོག 共 4 個
所在的段落分別是 1.1b, 2.32a, 2.35b, 3.110a, 如下圖

![nojump](https://cloud.githubusercontent.com/assets/13195099/12541983/4846e9fc-c358-11e5-8d11-c268b1a8d83a.jpg)

雖然都有搜到，但是如果按 next 箭頭，橘色 highlight 和畫面只會自動跳到 1.1b, 2.32a, 3.110a 的 དཀོན་མཆོག，不會跳到 2.35b 的 དཀོན་མཆོག
這是否屬於 #59 的範圍

**Comment by kmsheng** [comment]
@chiehan1 因為 https://github.com/karmapa/AdarshaIos/issues/72 , 建議此 issue 可以先關閉

**Comment by chiehan1** [comment]
因為 #72 , 此 issue 先關閉
