### ISSUE TITLE
新增 search in sutra 功能，輸入關鍵字按 search 後，可以跳到該經的第一個符合搜尋的字

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#58]
search in sutra 功能，輸入關鍵字按 search 後，可以跳到該經的第一個符合搜尋的字，這個字要顯示在畫面的第一行，除了標紅以外(所有符合的字都要標紅)，還要 highlight

**Comment by kmsheng** [comment]
@chiehan1  已在 v1.0.48 (1) 實作, 目前以黃色 ( highlight ) 與橘色 ( 聚焦的關鍵字 ) 搭配

**Comment by chiehan1** [comment]
目前輸入關鍵字後，可看到符合的字標成黃色，但是按鍵盤右下方的 return，並不會跳到這部經的第一個符合的字

**Comment by kmsheng** [comment]
@chiehan1 不是直接輸入關鍵字, 有符合的預設就會標出橘色了嗎?

**Comment by chiehan1** [comment]
現在標的橘色只是 pb 段落的第一個符合的字，並沒有標到經的第一個符合的字，
這個標橘色的字目前也不會顯示在螢幕畫面的第一行

**Comment by kmsheng** [comment]
@chiehan1 現在沒辦法保證一定會出現在螢幕上，因為現在沒辦法抓到 Text 裡的 Text 精確位置, 這個問題已在 https://github.com/karmapa/AdarshaIos/issues/59 提過, 也回報給 Facebook 了
現在能抓到精確位置的只有以 pb 為單位的文字區塊

**Comment by chiehan1** [comment]
因為 #72 , 此 issue 先關閉
