### ISSUE TITLE
新增 search in sutra 功能的 prev / next / close 按鈕

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#59]
prev / next 按鈕可以在當下的經的範圍內跳上一個或跳下一個符合搜尋條件的字，跳到的字要顯示在頁面的第一行，這個字除了標紅以外，還要 highlight

當 prev 跳到經文的第一個符合的字，再繼續按 prev 時，不需要跳到經文的最後一個符合的字。
反之亦然，
當 next 跳到經文的最後一個符合的字，再繼續按next 時，不需要跳回經文的第一個符合的字。

close 可以把 search bar 關掉。

**Comment by kmsheng** [comment]
@chiehan1 目前在 React Native 在 Text node 裡頭的 Text 不支援查詢相對位置, 以回報給官方 https://github.com/facebook/react-native/issues/5173

**Comment by chiehan1** [comment]
因為 #72 , 此 issue 先關閉
