### ISSUE TITLE
進階搜尋第三欄欄位名稱改為 འཁོར་ལོ། 

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#61]
下圖進階搜尋第三欄欄位名稱(綠色框框內的字)原本是 དཀའ། འཁོར་ལོ། 
請更改為 འཁོར་ལོ། 

![img_0129](https://cloud.githubusercontent.com/assets/13195099/12189567/e31a4d0a-b5f9-11e5-83b4-773a9c93219b.jpg)

**Comment by kmsheng** [comment]
@chiehan1  已在 v1.0.48 (1) 修正

**Comment by chiehan1** [comment]
test ok
thank you
