### ISSUE TITLE
內文工具列的 tab 圖示更改

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#62]
sutra biography 圖示改為
https://drive.google.com/open?id=0B7IngcS_Eo5Jd3ctYWcwZzdwelk

search in sutra 圖示改為
https://drive.google.com/open?id=0B7IngcS_Eo5JYmhYWE1jUkxEVms

**Comment by kmsheng** [comment]
@chiehan1  已在 v1.0.48 (1) 修正

**Comment by chiehan1** [comment]
test ok 
thank you
