### ISSUE TITLE
希望更改內文上方的經名 bar 和下方的 tool bar 背景顏色 

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#63]
希望更改內文上方的經名 bar 和下方的 tool bar 背景顏色，感謝
色碼 #1B8C90

如下圖
![page_1](https://cloud.githubusercontent.com/assets/13195099/12194246/7a8a7d8e-b629-11e5-9db9-70510ee5d07a.jpg)

**Comment by kmsheng** [comment]
@chiehan1 因為有半透明形式, 請提供 alpha 數值
目前設定為 rgba(27, 140, 144, 0.5)

**Comment by chiehan1** [comment]
我會請法海師重新界定 rgba 和 alpha 值，現在的顏色怪怪的

**Comment by chiehan1** [comment]
@kmsheng  請您重新設定為 rgba (27, 130, 134, 0.9)
感謝

**Comment by chiehan1** [comment]
測試 ok 
感謝
