### ISSUE TITLE
樹狀目錄上方的 category bar 和內文上方的經名 bar 的顏色區塊都要延伸到最上方

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#64]
樹狀目錄上方的 category bar 和內文上方的經名 bar 的顏色區塊都要延伸到最上方

![img_0130](https://cloud.githubusercontent.com/assets/13195099/12195992/5ed9fc4c-b636-11e5-8aca-6031a1119b81.jpg)

![img_0131](https://cloud.githubusercontent.com/assets/13195099/12195995/6100aed0-b636-11e5-973a-7d23b64b2770.jpg)

**Comment by kmsheng** [comment]
@chiehan1  已在 v1.0.48 (1) 修正這個問題

**Comment by chiehan1** [comment]
test ok 
thank you
