### ISSUE TITLE
Romanized Sanskrit font size problem.

### ISSUE THREAD

**Issue by yapcheahshen** [karmapa/AdarshaIos#65]
version : 1.0.45
Characters with diacritic mark have smaller size. (a+macron , n+tilde, etc) 
![img_1034 1](https://cloud.githubusercontent.com/assets/1085366/12221382/f240675c-b7d3-11e5-967c-f6d3c54b3a2a.PNG)

**Comment by kmsheng** [comment]
fixed in https://github.com/karmapa/AdarshaIos/issues/43
