### ISSUE TITLE
testwildcard.js 更新

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#66]
新增可區別 gyang 和 g.yang 的規則
testwildcard.js 已更新

https://github.com/karmapa17/jiangkangyur/blob/master/test/testwildcard.js

**Comment by kmsheng** [comment]
@chiehan1  已在 v1.0.48 (1) 修正, 下次麻煩要改的話在 tibetan 那個 repo 改吧

**Comment by chiehan1** [comment]
test ok
thank you
