### ISSUE TITLE
nextKeyword 閃退

### ISSUE THREAD

**Issue by yapcheahshen** [karmapa/AdarshaIos#67]
version 1.0.46(3)
steps to reproduce:
1) go to 1.1b
2) search in sutra , type "pa"
3) click NextKeyword several times
4) program unexpectedly quit.

**Comment by kmsheng** [comment]
@yapcheahshen 已在 v1.0.48 (1) 修正這個問題

**Comment by kmsheng** [comment]
commented 5 days ago, 如果沒有其他問題我就先關了
