### ISSUE TITLE
希望 向上捲動的字 不要和 手機最上方的導覽列 重疊

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#7]
希望 向上捲動的字 不要和 手機最上方的導覽列 重疊
![1 1](https://cloud.githubusercontent.com/assets/13195099/11630093/da21d6ae-9d36-11e5-83db-9ebf22e40a8e.PNG)

![1 2](https://cloud.githubusercontent.com/assets/13195099/11630101/e76c454c-9d36-11e5-97f6-14b8eee37a61.PNG)

**Comment by kmsheng** [comment]
please try v1.0.1 in iphone4s

**Comment by chiehan1** [comment]
Test ok!
Thank you!
