### ISSUE TITLE
希望能移除 volumn 頁的非大藏經字元

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#70]
如綠色框框所示

![volumncharacter](https://cloud.githubusercontent.com/assets/13195099/12473460/30a05d14-c04d-11e5-8ffc-faed03182bcd.jpg)

**Comment by kmsheng** [comment]
@yapcheahshen 請問一下這個  _@2  uti 的用意 ? 我是不是直接用 regexp 比對 uti 的格式去除比較快 ?

**Comment by kmsheng** [comment]
@yapcheahshen hi, 葉老師有看到這裡的問題嗎 ?

**Comment by yapcheahshen** [comment]
_開頭的uti 在資料庫中是必須存在的。
但APP可以選擇不顯示。
replace(/_@\d+/g,"")

yap

2016-01-22 17:53 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
@yapcheahshen 可以在文件上寫清楚這件事嗎? 不然不知道的人還以為 uti 只會有 \d+\.\d+[abcd] 這種格式

**Comment by yapcheahshen** [comment]
只有jiangkangyur 採用 \d+.\d+[abcd]
uti 的格式用戶可以自由設置，
開頭為_表示檔案的開頭到第一個 segment separator 為止的內容。
因為uti 必須唯一，所以系統自動補上 @數字。

2016-01-22 19:41 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
@chiehan1 已在 v1.0.50 (8) 修正

**Comment by chiehan1** [comment]
test ok thank you
