### ISSUE TITLE
內文點選下方的 biography icon ，顯示的 biography 內容希望能和經名一致

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#71]
這邊延續 #53 的例子，
選樹狀目錄的 
第10個 寶積部 
--> 第4個 ང 
--> 第2個 འཕགས་པ་**གང་པོས**་ཞུས་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ། ( 圖a, 綠色底線)

進入 pb 81.188a 的內文，經名已經一致，( 圖b, 綠色底線)

但是點選 biography icon 後，可以看到顯示的其實是上一個經的 biography 內容 (圖c, 橘色底線; 這是上一個經的經名), 這邊可以發現內容的經名 (橘色底線) 和經名列的經名 (綠色底線) 不一樣

回到內文往下滾到下一頁 pb 81.188b ( 圖d) 

再按 biography icon，才會顯示這一個經的 biography 內容  (圖e, 綠色底線; 這是這一個經的經名)

和 #53 的問題有點像，由內文抓到的 biography 內容會差一頁
![biography](https://cloud.githubusercontent.com/assets/13195099/12542292/1883194e-c35c-11e5-8cc5-4b130af49e99.jpg)

**Comment by kmsheng** [comment]
@chiehan1 已在 v1.0.50 (9) 修正

**Comment by chiehan1** [comment]
測試完成，感謝!
