### ISSUE TITLE
sutra id property 有括號的 biography 資料，無法顯示

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#74]
例如
從全文檢索進入 13.342a，
抓到的 sutra id tag 是 <sutra id="J8n"/>
但是 biographyForIOS.json 的 sutra id 格式是 "sutraid": "J8(n)"
所以進入內文後按 biography icon 顯示的內容是空白的

現在已把 biographyForIOS.json 的 "sutraid" 格式改為 "sutraid": "J8n"
以符合 jiangkangyur.kdb 的格式
請更換新的 json 檔
https://drive.google.com/open?id=0B7IngcS_Eo5JdUtvVk1QYUM5eWs
感謝!

**Comment by kmsheng** [comment]
@chiehan1 done in v1.0.50 (11)

**Comment by chiehan1** [comment]
test ok 
thank you
