### ISSUE TITLE
全文檢索 搜尋結果不齊全

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#75]
例如輸入 ga dag
前兩個搜尋結果顯示
1.2a 1.135b
和用 node.js 跑 testwildcard.js 的結果一致
q= ག་དག
match count 81
[ '1.2a)\nདགག་...ལ་ཨང་【ག་དག་】ན་ཨང་...པའི་\n',
  '1.135b)\nཟེར་...ེ་ཡལ་【ག་དག་】གམ། ས...ས་ཡལ་【ག་དག་\n】གམ། ས...ྱིས་\n',
(以下略)

但是 jiangkangyur 中以 ga dag 為雙音節的字串出現在
1.2a 1.7b 1.135b

搜尋結果漏了 1.7b

![img_0149](https://cloud.githubusercontent.com/assets/13195099/12605301/ad7ad64c-c4fe-11e5-8d12-09bc898cc8da.jpg)

**Comment by kmsheng** [comment]
@chiehan1 請參考我補的測試程式 https://github.com/karmapa/AdarshaIos/blob/master/test/filter.js , 的確沒有 1.7b 啊 ?

**Comment by chiehan1** [comment]
了解，那麼可能是 ksana 的設定

**Comment by kmsheng** [comment]
@yapcheahshen 請葉老師協助說明

**Comment by yapcheahshen** [comment]
更新 ksana-simple-api@1.5.22

依 頁做為輸出單元，
ksa.filter({db:db,q:q,phrase_sep:"།",field:""}
或
ksa.filter({db:db,q:q,phrase_sep:"།"}
會得到95筆，含1.7b

**Comment by chiehan1** [comment]
Test ok!
Thank you!
