### ISSUE TITLE
Conforming GPL

### ISSUE THREAD

**Issue by yapcheahshen** [karmapa/AdarshaIos#83]
Add https://github.com/karmapa/adarshaios in About page to conform with GPL.

**Comment by kmsheng** [comment]
https://github.com/karmapa/AdarshaIos/commit/7eeca4d7d5ffad81547ec47b28b3af1f1b7f0864

**Comment by kmsheng** [comment]
@yapcheahshen 請問 https://github.com/karmapa/AdarshaIos/commit/7eeca4d7d5ffad81547ec47b28b3af1f1b7f0864 有解決此 issue 嗎 ?

**Comment by yapcheahshen** [comment]
GPL 規範要求source file 和軟體一起釋出，
所以從app 要可以連到 github adarsha source code page

2016-02-02 12:45 GMT+08:00 kmsheng notifications@github.com:

**Comment by kmsheng** [comment]
done in v1.0.51(10)
