### ISSUE TITLE
和 Mac mini 同步，重開 app 白屏

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#84]
裝置 ipad4 mini

https://youtu.be/SJqeSWTMZnA

打開 Adarsha iOS 
和 Mac mini 同步，開始錄製
關掉 Adarsha iOS
再重新打開 Adarsha iOS
白屏

**Comment by kmsheng** [comment]
@chiehan1 這個目前我用模擬器重製不出來, 看來要借裝置實測了。

**Comment by kmsheng** [comment]
@chiehan1 請協助測試 v1.0.52 (7) 是否還有此問題

**Comment by chiehan1** [comment]
test ok 
thank you
