### ISSUE TITLE
全文檢索 快速下滑，再連點搜尋結果，內文頁會重覆開啟

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#85]
全文檢索搜尋欄輸入 b
搜尋結果顯示後
快速下滑 30 次以上
馬上連點搜尋結果
內文頁會重複開啟
按返回搜尋結果 (返回上一頁) 的箭頭
也會重複回到內文頁，或閃退

**Comment by kmsheng** [comment]
fixed in v1.0.51(10)

**Comment by chiehan1** [comment]
全文檢索搜尋欄輸入 b
搜尋結果顯示後
快速下滑 30 次以上
馬上連點搜尋結果
點進內文頁後
按返回搜尋結果 (返回上一頁) 的箭頭，沒反應
繼續持續按返回上一頁的箭頭，會閃退

**Comment by kmsheng** [comment]
@chiehan1 這是在 iphone4s 發生的嗎 ?

**Comment by kmsheng** [comment]
http://stackoverflow.com/questions/31666961/react-native-listview-recycling

**Comment by kmsheng** [comment]
https://github.com/facebook/react-native/issues/499#issuecomment-128836161

**Comment by kmsheng** [comment]
@chiehan1 確認是 memory leak, 目前看起來沒有好解法。硬要修的話, 往上 swipe 會卡卡的喔 ? ( 類似像內文頁那樣 )

**Comment by chiehan1** [comment]
那就先不用修，應該很少人會這樣測試
