### ISSUE TITLE
iphone 4s 從主畫面 ( Home screen ) 的 icon 開啟，過了 logo 畫面後，白屏

### ISSUE THREAD

**Issue by chiehan1** [karmapa/AdarshaIos#86]
從 icon 開啟，過了 logo 畫面後，白屏
![white](https://cloud.githubusercontent.com/assets/13195099/12774216/bd4743f6-ca7d-11e5-8de6-97ac9e0e2c0d.png)

但是從 testflight 的 open 可以開啟
![img_0007](https://cloud.githubusercontent.com/assets/13195099/12774261/177cdd36-ca7e-11e5-8af2-e1ebacf4d1f5.PNG)

**Comment by chiehan1** [comment]
iphone 4s 的狀態是全部重置後直接安裝 testflight 和 Adarsha iOS
系統是 9.2.1 (13D15)
Capacity 12.5G
Available 11.1G

**Comment by chiehan1** [comment]
從 testflight 開啟，過了 logo 畫面後，雖然也會白屏 2 - 3 秒，但是之後畫面會有個圓圈在轉，轉一下子以後就可以正常進入，
從主畫面的 icon 開啟，過了 logo 畫面後，會停留在白屏的畫面，無法再往下進入

**Comment by kmsheng** [comment]
@chiehan1 是只有從 testflight 開啟才會正常 ?

**Comment by chiehan1** [comment]
目前試了 8 次，從 icon 開停在白屏畫面，但從 testflight 可正常開啟
之前偶而可以從 icon 開啟，幾乎是開開關關十幾次才會有一次成功

**Comment by chiehan1** [comment]
~~從 icon 開啟停在白屏畫面，手機進入自動鎖定以後，第一次輸入密碼想解除自動鎖定會當機，第二次輸入密碼才能解除自動鎖定~~

**Comment by chiehan1** [comment]
~~從 icon 開啟停在白屏畫面，手機進入自動鎖定以後，第一次輸入密碼想解除自動鎖定會當機，第二次輸入密碼才能解除自動鎖定~~
更正，上面刪掉的這個情形有時出現有時正常

**Comment by kmsheng** [comment]
@chiehan1 請協助測試 v1.0.52 (7) 是否還有此現象

**Comment by chiehan1** [comment]
感謝，v1.0.52 (7) 可以從 icon 開啟
開啟的過程多了一個只顯示上方灰色 bar 和下方綠色 bar 的畫面
https://www.youtube.com/watch?v=WgGuixVRrhc

記錄了目前 iphone 4s 開啟過程：
先顯示 logo 
白畫面 
顯示灰色 bar 和綠色 bar 
白畫面，有等待的旋轉圓圈
進入樹狀目錄

另外在飛航模式也可開啟

**Comment by kmsheng** [comment]
@chiehan1 測了不少次，發現是 loading 轉動圖示的問題，所以先拿掉了。
其實 kdb 開檔也沒有很慢，所以我想影響應該不大。

最終的解法已實作在 v1.0.52 (10)，請參考。

**Comment by chiehan1** [comment]
已測試完成，v1.0.52 (10) 開啟都沒問題，感謝!
